name: publish npm repos CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        always-auth: true
        cache: 'npm'
        registry-url: 'https://registry.npmjs.org'

    - run: npm ci
    - run: npm run build

    - name: debug
      run: |
            npm config set //registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}
            cat /home/runner/work/_temp/.npmrc


    # 使用npm token发布
    - name: publish to npm repos
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

